abstract final class RoutePaths {
  static const login = '/login';
  static const register = '/register';
  static const forgotPassword = '/forgot-password';
  static const resetPassword = '/reset-password';
  static const home = '/';
  static const products = '/products';
  static const productDetail = '/product/:id';
  static const cart = '/cart';
  static const search = '/search';
  static const checkout = '/checkout';
  static const profile = '/profile';
  static const addresses = '/addresses';
  static const orders = '/orders';
  static const orderDetail = '/orders/:id';
  static const myReviews = '/my-reviews';
  static const shipmentTracking = '/shipment-tracking';
  static const guestOrderLookup = '/guest-order-lookup';
}
